### DISCUSSION TITLE
Large initial energy RMSE when finetuning

### DISCUSSION THREAD

**Discussion by tomdemeyere** [MDIL-SNU/SevenNet#191] [Q&A]
I started to finetune the `SevenNet-l3i5` model with a dataset containing ~ 3000 structures of slabs and nanoparticles. The original energy RMSE is extremely high (2500 eV/atom) while forces are ok (400 meV/Å). Is there something I don't understand with energy references?

Here is my `finetune.yaml`:

``` yaml
model:
  act_gate:
    e: silu
    o: tanh
  act_radial: silu
  act_scalar:
    e: silu
    o: tanh
  channel: 128
  chemical_species: auto
  cuequivariance_config: {}
  cutoff: 5.0
  cutoff_function:
    cutoff_function_name: poly_cut
    poly_cut_p_value: 6
  interaction_type: nequip
  irreps_manual:
  - 128x0e
  - 128x0e+64x1e+32x2e+32x3e
  - 128x0e+64x1e+32x2e+32x3e
  - 128x0e+64x1e+32x2e+32x3e
  - 128x0e+64x1e+32x2e+32x3e
  - 128x0e
  is_parity: false
  lmax: 3
  lmax_edge: -1
  lmax_node: -1
  num_convolution_layer: 5
  radial_basis:
    bessel_basis_num: 8
    radial_basis_name: bessel
  readout_as_fcn: false
  self_connection_type: linear
  train_denominator: false
  train_shift_scale: true
  train_avg_num_neigh : true 
  use_bias_in_linear: false
  use_modal_node_embedding: false
  use_modal_output_block: false
  use_modal_self_inter_intro: false
  use_modal_self_inter_outro: false
  weight_nn_hidden_neurons:
  - 64
  - 64

train:
    random_seed: 1
    is_train_stress: False
    epoch: 100

    force_loss_weight : 100.0
    stress_loss_weight: 0.0
    loss: huber
    loss_param:
        delta: 0.01

    optimizer: adamw
    optim_param:
        lr: 0.0002
    scheduler: 'exponentiallr'
    scheduler_param:
        gamma: 0.99

    csv_log: log.csv

    error_record:
        - ['Energy', 'RMSE']
        - ['Force', 'RMSE']
        - ['Stress', 'RMSE']
        - ['TotalLoss', 'None']

    loss_param: {}

    #scheduler: onecyclelr
    #scheduler_param:
    #    anneal_strategy: cos
    #    div_factor: 25.0
    #    epochs: 2
    #    final_div_factor: 10000.0
    #    max_lr: 0.0002
    #    pct_start: 0.005
    #    total_steps: 1007534
    #stress_loss_weight: 1.0e-06
    train_shuffle: true
    use_weight: false

    per_epoch: 10

    continue:
        reset_optimizer: True
        reset_scheduler: True
        reset_epoch: True
        checkpoint: checkpoint_l3i5.pth
        use_statistic_values_of_checkpoint: False

data:
  batch_size: 8
  compute_statistics: true
  #use_species_wise_shift_scale: True
  shift: 'elemwise_reference_energies'
  data_format: ase
  data_format_args: {}
  load_trainset_path: training_set.xyz
  load_validset_path: validation_set.xyz
  preprocess_num_cores: 1
  use_modal_wise_scale: false
  use_modal_wise_shift: false
```
