### DISCUSSION TITLE
Fine tune with additional elements

### DISCUSSION THREAD

**Discussion by turbosonics** [MDIL-SNU/SevenNet#68] [Q&A]
I have a Seven Net model that I trained for silica structure AIMDs. Using this model, I tried to fine tune a new model using a new training set that contains water and silica interaction AIMDs. Target is to check if I can fine-tune train a model for bulk and surface-water interaction. 

Then I see 
`ValueError: Chemical species in checkpoint is not compatible`

And the last line of log.sevenn is
`Ignore chemical species in yaml, use checkpoint`

It looks like the issue is that the new training set for the fine-tune training contains H atoms which were not included in prior training set. Any way to resolve this situation? I didn't see any options regarding elements (or chemical species) in the input file example... 

Following is the script that I used for the fine tuning. The input file contains the same hyperparameters with input file of from-scratch training of silica model. 

```
model:
    chemical_species: 'Auto'
    cutoff: 6.0
    channel: 64
    is_parity: True
    lmax: 1
    num_convolution_layer: 3
    irreps_manual:
        - "64x0e"
        - "64x0e+64x1e"
        - "64x0e+64x1e"
        - "64x0e"

    weight_nn_hidden_neurons: [64, 64]
    radial_basis:
        radial_basis_name: 'bessel'
        bessel_basis_num: 10
    cutoff_function:
        cutoff_function_name: 'XPLOR'
        cutoff_on: 4.5

    act_gate: {'e': 'silu', 'o': 'tanh'}
    act_scalar: {'e': 'silu', 'o': 'tanh'}

    conv_denominator: "avg_num_neigh"
    train_shift_scale: True
    train_denominator: True
    self_connection_type: 'nequip'

train:
    train_shuffle: True
    random_seed: 123
    is_train_stress: True
    epoch: 2000

    loss: 'Huber'
    loss_param:
        delta: 0.01

    optimizer: 'adam'
    optim_param:
        lr: 0.002
    scheduler: 'ReduceLROnPlateau'
    scheduler_param:
        factor: 0.5
        patience: 50
    force_loss_weight: 1.0
    stress_loss_weight: 0.01

    per_epoch: 10
    error_record:
        - ['Energy', 'RMSE']
        - ['Force', 'RMSE']
        - ['Stress', 'RMSE']
        - ['Energy', 'MAE']
        - ['Force', 'MAE']
        - ['Stress', 'MAE']
        - ['Energy', 'Loss']
        - ['Force', 'Loss']
        - ['Stress', 'Loss']
        - ['TotalLoss', 'None']

    continue:
        reset_optimizer: True
        reset_scheduler: True
        reset_epoch: True
        checkpoint: '${PTMODEL_DIR}/${PTMODEL_NAME}'
        # Set True to use shift, scale, and avg_num_neigh from checkpoint (highly recommended)
        use_statistic_values_of_checkpoint: True

data:
    data_shuffle: True
    batch_size: 12
    data_divide_ratio: 0.2
    data_format: 'ase'
    load_dataset_path: ['${GEOMETRY_DIR}/${GEOMETRY_TRAIN_NAME}']
```
